/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login User */
        post: operations["login_user_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/utils": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_utils_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User Me */
        get: operations["read_user_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchants */
        get: operations["read_merchants_api_v1_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Types */
        get: operations["read_merchant_types_api_v1_merchants_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant */
        get: operations["read_merchant_api_v1_merchants__merchant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Photos */
        get: operations["read_merchant_photos_api_v1_merchants__merchant_id__photos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Reviews */
        get: operations["read_merchant_reviews_api_v1_merchants__merchant_id__reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Types Detail */
        get: operations["read_merchant_types_detail_api_v1_merchants__merchant_id__types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}/opening-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Opening Hours */
        get: operations["read_merchant_opening_hours_api_v1_merchants__merchant_id__opening_hours_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchants/{merchant_id}/amenities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Amenities */
        get: operations["read_merchant_amenities_api_v1_merchants__merchant_id__amenities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/merchant-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Merchant Types */
        get: operations["read_merchant_types_api_v1_merchant_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmenityPublic */
        AmenityPublic: {
            /** Id */
            id: number;
            /** Takeout */
            takeout: boolean | null;
            /** Dine In */
            dine_in: boolean | null;
            /** Outdoor Seating */
            outdoor_seating: boolean | null;
            /** Reservable */
            reservable: boolean | null;
            /** Serves Breakfast */
            serves_breakfast: boolean | null;
            /** Serves Lunch */
            serves_lunch: boolean | null;
            /** Serves Dinner */
            serves_dinner: boolean | null;
            /** Serves Brunch */
            serves_brunch: boolean | null;
            /** Serves Beer */
            serves_beer: boolean | null;
            /** Serves Wine */
            serves_wine: boolean | null;
            /** Serves Vegetarian Food */
            serves_vegetarian_food: boolean | null;
            /** Good For Children */
            good_for_children: boolean | null;
            /** Good For Groups */
            good_for_groups: boolean | null;
            /** Accepts Credit Cards */
            accepts_credit_cards: boolean | null;
            /** Accepts Debit Cards */
            accepts_debit_cards: boolean | null;
            /** Accepts Cash Only */
            accepts_cash_only: boolean | null;
            /** Accepts Nfc */
            accepts_nfc: boolean | null;
            /** Free Parking */
            free_parking: boolean | null;
            /** Paid Parking */
            paid_parking: boolean | null;
            /** Valet Parking */
            valet_parking: boolean | null;
            /** Wheelchair Entrance */
            wheelchair_entrance: boolean | null;
            /** Wheelchair Restroom */
            wheelchair_restroom: boolean | null;
            /** Wheelchair Seating */
            wheelchair_seating: boolean | null;
            /** Restroom */
            restroom: boolean | null;
        };
        /** Body_login_user_api_v1_auth_login_post */
        Body_login_user_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MerchantDetail */
        MerchantDetail: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string | null;
            /** Name */
            name: string;
            /** Primary Type */
            primary_type: string | null;
            /** Formatted Address */
            formatted_address: string | null;
            /** Short Address */
            short_address: string | null;
            /** Phone National */
            phone_national: string | null;
            /** Phone International */
            phone_international: string | null;
            /** Website */
            website: string | null;
            /** Photo Url */
            photo_url: string | null;
            /** Description */
            description: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Rating */
            rating: number | null;
            /** User Rating Count */
            user_rating_count: number | null;
        };
        /** MerchantListItem */
        MerchantListItem: {
            /** Id */
            id: number | null;
            /** Display Name */
            display_name: string | null;
            /** Name */
            name: string;
            /** Primary Type */
            primary_type: string | null;
            /** Short Address */
            short_address: string | null;
            /** Rating */
            rating: number | null;
            /** User Rating Count */
            user_rating_count: number | null;
            /** Type Count */
            type_count: number;
            /** Photo Url */
            photo_url: string | null;
        };
        /** MerchantTypePublic */
        MerchantTypePublic: {
            /** Id */
            id: number;
            /** Type Name */
            type_name: string;
        };
        /** MerchantsPublic */
        MerchantsPublic: {
            /** Data */
            data: components["schemas"]["MerchantListItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /** OpeningHoursPublic */
        OpeningHoursPublic: {
            /** Id */
            id: number;
            /** Is Open Now */
            is_open_now: boolean | null;
            /** Monday */
            monday: string | null;
            /** Tuesday */
            tuesday: string | null;
            /** Wednesday */
            wednesday: string | null;
            /** Thursday */
            thursday: string | null;
            /** Friday */
            friday: string | null;
            /** Saturday */
            saturday: string | null;
            /** Sunday */
            sunday: string | null;
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
            /** Has Next */
            has_next: boolean;
            /** Has Previous */
            has_previous: boolean;
        };
        /** PhotoPublic */
        PhotoPublic: {
            /** Id */
            id: number;
            /** Photo Reference */
            photo_reference: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Author Name */
            author_name: string | null;
            /** Is Primary */
            is_primary: boolean;
            /** Order */
            order: number;
        };
        /** ReviewPublic */
        ReviewPublic: {
            /** Id */
            id: number;
            /** Google Review Id */
            google_review_id: string;
            /** Rating */
            rating: number;
            /** Text */
            text: string | null;
            /** Author Name */
            author_name: string | null;
            /** Author Photo Uri */
            author_photo_uri: string | null;
            /** Published At */
            published_at: string | null;
            /** Relative Time */
            relative_time: string | null;
        };
        /** Status */
        Status: {
            /** Ok */
            ok: boolean;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserPublic */
        UserPublic: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_user_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_user_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_utils_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    read_user_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    read_merchants_api_v1_merchants_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                type?: string | null;
                lang?: "english" | "indonesian";
                sort_by?: "name" | "rating" | "distance" | "created_at";
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_types_api_v1_merchants_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    read_merchant_api_v1_merchants__merchant_id__get: {
        parameters: {
            query?: {
                lang?: "english" | "indonesian";
            };
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_photos_api_v1_merchants__merchant_id__photos_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_reviews_api_v1_merchants__merchant_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_types_detail_api_v1_merchants__merchant_id__types_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantTypePublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_opening_hours_api_v1_merchants__merchant_id__opening_hours_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpeningHoursPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_amenities_api_v1_merchants__merchant_id__amenities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                merchant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmenityPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_merchant_types_api_v1_merchant_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
}
